In [1]:
import numpy as np
from sklearn.metrics import accuracy_score

In [2]:
folder_path = '/Users/clidev/Desktop/Capstone_Project/pnumonia/X-Ray-CNN/image_as_numpy/'

X_train = np.load(folder_path + 'X_train.npy')
X_validate = np.load(folder_path + 'X_validate.npy')
X_test = np.load(folder_path + 'X_test.npy')

y_train = np.load(folder_path + 'y_train.npy')
y_validate = np.load(folder_path + 'y_validate.npy')
y_test = np.load(folder_path + 'y_test.npy')

In [3]:
path = '/Users/clidev/Desktop/Capstone_Project/pnumonia/X-Ray-CNN/postprocess_output/BaselineNet_ADAM_epoch150/'

In [4]:
train_evaluate = np.load(path + 'train_evaluate.npy')
validate_evaluate = np.load(path + 'validate_evaluate.npy')
test_evaluate = np.load(path + 'test_evaluate.npy')

In [5]:
y_train_pred = np.load(path + 'y_train_pred.npy')
y_validate_pred = np.load(path + 'y_validate_pred.npy')
y_test_pred = np.load(path + 'y_test_pred.npy')

In [6]:
y_train_proba = np.load(path + 'y_train_proba.npy')
y_validate_proba = np.load(path + 'y_validate_proba.npy')
y_test_proba = np.load(path + 'y_test_proba.npy')

## Look at evaluation

In [7]:
train_evaluate

array([8.04744496, 0.50037869])

In [8]:
validate_evaluate

array([8.05094588, 0.5       ])

In [9]:
test_evaluate

array([8.0450646, 0.5      ])

## Look at prediction

In [10]:
y_train_pred = y_train_pred[:,0]

In [11]:
y_train_pred = y_train_pred.astype(int)

In [12]:
accuracy_score(y_train, y_train_pred)

0.5001262307498107